name: Bug Report
description: Report a bug to help us improve the app.
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Description
        **Describe the bug**:
        - Please provide a detailed description of the bug.

        ## Expected Behavior
        **What did you expect to happen?**

        ## Steps to Reproduce
        1. Step 1
        2. Step 2
        3. Step 3

        ## Screenshots
        If possible, attach screenshots to help better understand the issue.

  - type: input
    attributes:
      label: "What did you expect to happen?"
      description: "Describe what you expected to happen instead of the bug."
      placeholder: "Describe the expected behavior here."
      required: true

  - type: input
    attributes:
      label: "Steps to reproduce"
      description: "Please provide the steps to reproduce the bug."
      placeholder: "e.g. 1. Open the app, 2. Click on 'Login'"
      required: true

  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Provide any additional information that might be useful."
      placeholder: "Include any relevant context or configurations (optional)."
      required: false

  - type: input
    attributes:
      label: "Screenshots"
      description: "If possible, upload any screenshots that could help us understand the issue."
      placeholder: "Upload a screenshot (optional)"
      required: false