name: "Bug Report"
description: "Use this template to report a bug."
labels: ["bug"]
body:
  - type: "input"
    attributes:
      label: "Title"
      description: "Provide a short title for the bug."
      placeholder: "e.g. App crashes when I click the button"
      required: true
  - type: "textarea"
    attributes:
      label: "Bug Description"
      description: "Please describe the bug in detail."
      placeholder: "What steps did you take before encountering this bug?"
      required: true
  - type: "textarea"
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen?"
      required: true
  - type: "textarea"
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
      required: false