name: Bug Report
description: Report a bug to help us improve the app.
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Description
        **Describe the bug**:
        - Please provide a detailed description of the bug.

        ## Expected Behavior
        **What did you expect to happen?**

        ## Steps to Reproduce
        1. Step 1
        2. Step 2
        3. Step 3

        ## Screenshots
        If possible, attach screenshots to help better understand the issue.

  - type: input
    attributes:
      label: What did you expect to happen?
      description: Describe what you expected to happen instead of the bug.
      placeholder: Describe the expected behavior here.
