name: Feature Request
description: Suggest a new feature or improvement for the app.
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Description
        **Describe the feature or improvement you suggest**:
        - Provide a detailed description of the feature you'd like to see in the app.

        ## Benefits of the Feature
        **How would this feature improve the app?**

        ## Why is this Feature Important?
        **Why do you think this feature should be added?**
        
        ## Additional Context
        If applicable, provide any additional information or context that might be helpful.

  - type: input
    attributes:
      label: "Feature Description"
      description: "Describe the feature or improvement you suggest."
      placeholder: "Describe the new feature or improvement you think would be useful."
      required: true

  - type: input
    attributes:
      label: "Benefits of the Feature"
      description: "How would this feature improve the app?"
      placeholder: "Describe the potential benefits this feature would bring."
      required: true

  - type: input
    attributes:
      label: "Why is this Feature Important?"
      description: "Explain why you think this feature should be added."
      placeholder: "Provide reasoning behind your request."
      required: true

  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Provide any additional information or context that might be helpful."
      placeholder: "Include any relevant context or ideas related to this feature (optional)."
      required: false